### ISSUE TITLE
Several Issues with UI

### ISSUE THREAD

**Issue by darkAco** [Angel-125/Pathfinder#13]
Hey there.
Just look into this one if you have spare time, since it at least involves one other mod.

When I try to use the "Review Data" Action on a terrain sat, nothing happens and the alt+f12 debug log show errors like 'RemoteTec: BaseEvent invokeException by 'ReviewData' with message: Object reference not set to an instance of an object.'

I'm pretty unsure where these errors come from.

RemoteTech Version 1.8.9
Pathfinder Version 1.21
Kerbal Space Program: 1.3.1

All of the above are the most recent Version (01.03.2018).
In addition, I tried the pre-release Version of WildBlueTools, which changes nothing on that issue.

I also have other mods of yours installed, like Airships, DSEV and Buffalo.
All of them happen to behave rather strangely from time to time in my game which leads to the assumption that there is something going wrong on my part in the background - but im not sure.

**Comment by DeltaDizzy** [comment]
Try to remove mods until you have the fewest mods and the issue still happens. This may you know it isn't a conflict with another mod.

**Comment by MrKiel** [comment]
Hi, 
I too have this issue with the Review Data button on the Telescope - I've included a screenshot so that @Angel-125 can check against what it's supposed to look like in case there are any differences:

![20180603011021_1](https://user-images.githubusercontent.com/10761194/40881923-1139ac38-66cb-11e8-8dfd-4ca3e0306b35.jpg)
@darkAco Did you manage to track down which mod was causing it?

EDIT: Looking at it more, I think there may be an issue with the Deneye alone. It does gather scopetime (experiments using scopetime complete successfully), but if there's supposed to be a built-in experiment then I'm afraid it doesn't appear to work. 

EDIT2: The TERRAIN Scanner has the same issue.

Or it could be a conflict with another mod.

**Comment by Angel-125** [comment]
This is tough because it's hard to tell where the issue us. Is Remote Tech updated for KSP 1.4.5?
